id: alien4cloud-premium-workspace
name: Alien 4 Cloud Premium Workspaces.
version: ${project.version}
description: Workspaces management.
configuration_class: org.alien4cloud.workspace.PluginConfiguration
ui_entry_point: scripts/plugin.js
